---
- name: restart keepalived
  ansible.builtin.service:
    name: "{{ keepalived_service_name }}"
    state: restarted
  register: _servicestart

- name: reload keepalived
  ansible.builtin.service:
    name: "{{ keepalived_service_name }}"
    state: Reload
  register: _servicereload
  when:
    - _servicestart is not changed
    - _servicestart is not defined